# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "ohci_pci" "ehci_pci" "ahci" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/3cfca75c-799a-4efe-8f59-552930d3cf75";
      fsType = "btrfs";
      options = "autodefrag,compress=lzo";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/4ffede4e-6939-4355-b420-33ad3b92b954"; }
    ];

  nix.maxJobs = 2;
  virtualisation.virtualbox.guest.enable = true;
}
